name: bug test sundar 2
description: Tests out env settings
branding:
  icon: activity
  color: blue
inputs:
  - name: ProductionEnvReviewer
    type: string
  - name: DeploySecret
    type: string
    is-secret: true
configs:
  repo-metadata:
    parameters:
      secrets:
        - name: DEV_SPN_ID
          value: '${{inputs.DeploySecret}}'
        - name: DEV_SPN_ID_2
          value: hii
      topics:
        - rails
        - sql
  branches:
    - name: rule1
      parameters:
        enforce-admins: true
        dismiss-stale-reviews: true
        require-code-owner-reviews: true
        required-approving-review-count: 1
        allow-force-pushes: false
        allow-deletions: false
    - name: rule2
      parameters:
        enforce-admins: true
        dismiss-stale-reviews: true
        require-code-owner-reviews: true
        required-approving-review-count: 5
        allow-force-pushes: false
        allow-deletions: false
    - name: rule3
      parameters:
        enforce-admins: true
    - name: rule4
      parameters:
        dismiss-stale-reviews: true
    - name: rule5
      parameters:
        require-code-owner-reviews: true
    - name: rule6
      parameters:
        allow-force-pushes: true
    - name: rule7
      parameters:
        allow-deletions: true
